FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install --production

FROM node:20-alpine
WORKDIR /app
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
COPY --from=builder /app/node_modules ./node_modules
COPY package.json server.js ./
ARG APP_VERSION=v1
ENV APP_VERSION=${APP_VERSION}
USER appuser
EXPOSE 8080
CMD ["node", "server.js"]
