apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-ai-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vijaynaik1117/project-ai.git
    targetRevision: dev
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
